# Generated by Django 2.2.6 on 2020-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.CharField(max_length=32, verbose_name='业务ID')),
                ('bk_biz_name', models.CharField(max_length=128, verbose_name='业务名称')),
            ],
            options={
                'verbose_name': '业务信息',
                'verbose_name_plural': '业务信息',
                'db_table': 'business_info',
            },
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_cloud_id', models.CharField(max_length=32, verbose_name='云区域ID')),
                ('bk_cpu', models.IntegerField(blank=True, null=True, verbose_name='核数')),
                ('bk_os_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统名称')),
                ('bk_host_id', models.IntegerField(verbose_name='主机ID')),
                ('bk_host_innerip', models.CharField(max_length=32, verbose_name='内网IP')),
                ('bk_os_bit', models.CharField(max_length=8, verbose_name='位数')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
                'db_table': 'host_info',
            },
        ),
        migrations.CreateModel(
            name='MissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('mission_content', models.TextField(verbose_name='任务内容')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
                'db_table': 'mission_info',
            },
        ),
        migrations.CreateModel(
            name='MissionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(max_length=128, verbose_name='异步任务ID')),
                ('business_name', models.CharField(max_length=128, verbose_name='业务名称')),
                ('mission_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('machine_num', models.IntegerField(verbose_name='机器数')),
                ('status', models.CharField(choices=[('success', '执行成功'), ('doing', '执行中'), ('fail', '失败')], max_length=32, verbose_name='执行状态')),
                ('operator', models.CharField(max_length=32, verbose_name='操作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务记录',
                'verbose_name_plural': '任务记录',
                'db_table': 'mission_record',
            },
        ),
    ]
