# Generated by Django 2.2.6 on 2020-06-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.CharField(max_length=32, verbose_name='业务ID')),
                ('bk_biz_name', models.CharField(max_length=128, verbose_name='业务名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务信息',
                'verbose_name_plural': '业务信息',
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_cloud_id', models.CharField(max_length=32, verbose_name='云区域ID')),
                ('bk_cpu', models.IntegerField(blank=True, null=True, verbose_name='核数')),
                ('bk_os_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统名称')),
                ('bk_host_id', models.IntegerField(verbose_name='主机ID')),
                ('bk_host_innerip', models.CharField(max_length=32, verbose_name='内网IP')),
                ('bk_os_bit', models.CharField(max_length=8, verbose_name='位数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bk_biz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_host', to='home_application.Business', verbose_name='所属业务')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
                'db_table': 'host',
            },
        ),
        migrations.RenameModel(
            old_name='MissionInfo',
            new_name='Mission',
        ),
        migrations.DeleteModel(
            name='BusinessInfo',
        ),
        migrations.DeleteModel(
            name='HostInfo',
        ),
        migrations.RemoveField(
            model_name='missionrecord',
            name='celery_id',
        ),
        migrations.AlterField(
            model_name='missionrecord',
            name='status',
            field=models.CharField(choices=[('success', '执行成功'), ('doing', '执行中'), ('fail', '执行失败')], default='doing', max_length=32, verbose_name='执行状态'),
        ),
        migrations.AlterModelTable(
            name='mission',
            table='mission',
        ),
    ]
