# Generated by Django 2.2.6 on 2020-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('success', '执行成功'), ('doing', '执行中'), ('fail', '失败')], max_length=32, null=True, verbose_name='执行状态'),
        ),
    ]
