# Generated by Django 2.2.6 on 2020-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='bk_host_id',
            field=models.IntegerField(verbose_name='主机ID'),
        ),
    ]
