# Generated by Django 2.2.6 on 2020-06-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBkToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_token', models.TextField(verbose_name='登录用户的bk_token')),
            ],
            options={
                'verbose_name': '登录用户的bk_token',
                'verbose_name_plural': '登录用户的bk_token',
                'db_table': 'login_bk_token',
            },
        ),
    ]
