# Generated by Django 2.2.6 on 2020-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastExecuteScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.CharField(default='', max_length=100)),
                ('bk_cloud_id', models.CharField(default='', max_length=100)),
                ('bk_host_innerip', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
