# Generated by Django 2.2.6 on 2020-06-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_auto_20200612_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionrecord',
            name='celery_id',
        ),
    ]
