# Generated by Django 2.2.6 on 2020-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='bk_biz_id',
            field=models.IntegerField(verbose_name='所属业务的ID'),
        ),
    ]
