# Generated by Django 2.2.6 on 2020-06-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_remove_missionrecord_celery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='status',
            field=models.CharField(choices=[('success', '执行成功'), ('doing', '执行中'), ('fail', '失败')], default='执行中', max_length=32, verbose_name='执行状态'),
        ),
    ]
