# Generated by Django 2.2.6 on 2020-05-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_add_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastexecutescript',
            old_name='bk_host_innerip',
            new_name='bk_host_ip',
        ),
    ]
