# Generated by Django 2.2.6 on 2020-06-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20200610_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MisisonInfo',
            new_name='MissionInfo',
        ),
    ]
