# Generated by Django 2.2.6 on 2020-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_auto_20200531_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptJobRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default='', max_length=100)),
                ('business', models.CharField(blank=True, max_length=100, null=True)),
                ('mission', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('machine_num', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
