# Generated by Django 2.2.6 on 2020-06-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0005_scriptjobrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptjobrecord',
            name='task_id',
        ),
    ]
