# Generated by Django 2.2.6 on 2020-06-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0005_auto_20200612_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='status',
            field=models.CharField(choices=[('success', '执行成功'), ('doing', '执行中'), ('fail', '执行失败')], default='doing', max_length=32, verbose_name='执行状态'),
        ),
    ]
