# Generated by Django 2.2.6 on 2020-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_auto_20200628_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='job_instance_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务实例ID'),
        ),
    ]
