# Generated by Django 2.2.6 on 2020-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_remove_scriptjobrecord_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptjobrecord',
            name='operator',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
