# Generated by Django 2.2.6 on 2020-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0007_auto_20200628_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_token', models.TextField(verbose_name='登录用户的bk_token')),
            ],
            options={
                'verbose_name': 'bk_token',
                'verbose_name_plural': 'bk_token',
                'db_table': 'bk_token',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
