# Generated by Django 2.2.6 on 2020-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0008_auto_20200628_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='status',
            field=models.CharField(choices=[('1', '未执行'), ('2', '正在执行'), ('3', '执行成功'), ('4', '执行失败'), ('5', '跳过'), ('6', '忽略错误'), ('7', '等待用户'), ('8', '手动结束'), ('9', '状态异常'), ('10', '步骤强制终止中'), ('11', '步骤强制终止成功'), ('12', '步骤强制终止失败'), ('13', '提交失败')], default='1', max_length=32, verbose_name='执行状态'),
        ),
    ]
