# Generated by Django 2.2.6 on 2020-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0008_businessinfo_hostinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='bk_host_innerip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='bk_os_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
