# Generated by Django 2.2.6 on 2020-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0009_auto_20200608_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name': '业务信息', 'verbose_name_plural': '业务信息'},
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='bk_biz_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='bk_biz_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='businessinfo',
            table='business_info',
        ),
    ]
